%YAML:1.0

# openFABMAPexe Settings File

#---------------------------------------------------------------------------

FilePaths:
   #The training data video should be of disjoint, non-overlapping scenes
   #and should not visit the same location more than once

   TrainPath: "openFabmapPoziomo/srodowisko/list"

   #The test video should not overlap with the training video but should
   #have similar environment types.

   TestPath: "spl/train/list"

   #The test recognize video should not overlap with the test video but should
   #have similar environment types.

   TestRecPath: "spl/SP_PUT_CM_1_test/Test3/"

   #All feature descriptors extracted from the training data. Used to
   #create the vocabulary/codebook

   TrainFeatDesc: "vocabularytraindata.yml"

   #All bag-of-words type whole image descriptors extracted from the 
   #training data. Used to create the chow-liu tree and used in the
   #FabMap 'new place' likelihood calculation

   TrainImagDesc: "BOWtraindata.yml"
   
   #The vocabulary/codebook itself

   Vocabulary: "vocabulary.yml"
   
   #The Chow-Liu Tree itself

   ChowLiuTree: "tree.yml"

   #The FabMap Test

   TestImageDesc: "BOWtestdata.yml"

   #The FabMap Test recognize

   TestRecImageDesc: "BOWtestrecdata.yml"

   #The FabMap results

   FabMapResults: "results.txt"

#---------------------------------------------------------------------------

# openFABMAP running mode:

# "ShowFeatures"
# "GenerateVocabTrainData"
# "TrainVocabulary"
# "GenerateFABMAPTrainData"
# "TrainChowLiuTree"
# "GenerateFABMAPTestData"
# "RunOpenFABMAP"

#Function: "TrainChowLiuTree"
Function: "RunOpenFABMAP"

#---------------------------------------------------------------------------

ChowLiuOptions:

   # a large amount of data is required to store all mutual information from
   # which the minimum spanning tree is created. e.g. an 8000 word codebook 
   # requires 1.2 Gb RAM. Increasing the threshold results in information being 
   # discarded, and a lower memory requirement. Too high a threshold may result 
   # in necessary information being discarded and the tree not being created.
   #A threshold of 0 takes longer and may fail due to memory requirements

   Train: 0
   LowerInfoBound: 0.0005

#---------------------------------------------------------------------------

# Method to add new location to the FabMap location list
# "All"
# "NewMaximumOnly"

FabMapPlaceAddition: "All"

openFabMapOptions:

   #Detector Model

   PzGe: 0.39005
   PzGne: 0.000816887

   #The method to calculate the likelihood of a 'new location'
   #Note, FAB-MAP2.0 cannot use mean-field
   # "Sampled"
   # "Meanfield"

   NewPlaceMethod: "Sampled"

   #if using "sampled" method how many samples from training data to use

   NumSamples: 800

   # The option to switch off FabMap's feature dependency model (Chow-Liu tree)
   # in the likelihood calculations
   # "Naive"
   # "ChowLiu"

   BayesMethod: "ChowLiu"

   # The option to switch on and off the addition of a simple motion model
   # which assumes links between sequential additions to the query space.
   # 0 for False, 1 for True

   SimpleMotion: 0

   # Which version of openFABMAP to run
   # "FABMAP1"
   # "FABMAPLUT"
   # "FABMAPFBO"
   # "FABMAP2"

   FabMapVersion: "FABMAP2"
      
   #FabMap1:

      # no additional options
      
   FabMapLUT:

      # precision with which to store precomputed values (decimal places)

      Precision: 6

   FabMapFBO:
      # The loglikelihood bound beneath the best hypothesis at which other
      # hypotheses are always retained

      RejectionThreshold: 1e-6
      
      # The likelihood bound of a hypothesis 'overtaking' the current best 
      # hypothesis, below which hypotheses are discarded. Used to compute delta

      PsGd: 1e-6

      # The largest value of delta when computing it via the bisection method

      BisectionStart: 512

      # The number of iterations to perform the bisection. Bisection accuracy = 
      # BisectionStart / 2^BisectionIts

      BisectionIts: 9
      

   #FabMap2:

      # no additional options

#---------------------------------------------------------------------------
