%YAML:1.0

# WiFi-FAB-MAP setting file derived from openFABMAPexe Settings File

#---------------------------------------------------------------------------

FilePaths:
   
   #The Chow-Liu Tree itself

   ChowLiuTree: "tree.yml"
   
#---------------------------------------------------------------------------

ChowLiuOptions:

   # a large amount of data is required to store all mutual information from
   # which the minimum spanning tree is created. e.g. an 8000 word codebook 
   # requires 1.2 Gb RAM. Increasing the threshold results in information being 
   # discarded, and a lower memory requirement. Too high a threshold may result 
   # in necessary information being discarded and the tree not being created.
   #A threshold of 0 takes longer and may fail due to memory requirements

   Train: 0
   LowerInfoBound: 0.0005

#---------------------------------------------------------------------------


openFabMapOptions:

   #Detector Model

   PzGe: 0.31349
   PzGne: 0.0004285

#---------------------------------------------------------------------------
